Airbnb:Fetching Listings with server components | Fav Functionality
layout.tsx: wrap children in to single div.
pages.tsx: add listings as a card in home page.
listing card component & direct server action: we will load newly created listings from our database to display right there on the index page.

Empty state.tsx: empty state component
when nothing is selected (No exact matches) will be displayed on home page.
getListings.ts: created an action since home is a server componenent we can call database directly and we wont need to create api call for that.

listings card: Uploaded Images will be displayed as a card here
HeartButton.tsx : Add Heart Icon to add the place in to User Wish List.
useFavorite.ts: add hooks && favoriting and unfavoriting functionality && make the listings favorite and unfavorite by id.

Error: Only plain components can be passes to client componentsfrom server components date objects are not supported Bug Fixing: we will use safeListings instead of listings and we will pass string in created at instead of date object